services:
  gameflix_db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: gameflix_db
      MYSQL_USER: jt
      MYSQL_PASSWORD: 1234
    ports:
      - "3307:3306"

  app:
    image: gameflix-backend
    depends_on:
      - gameflix_db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://gameflix_db:3306/gameflix_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: jt
      SPRING_DATASOURCE_PASSWORD: 1234